### ISSUE TITLE
Selecting time

### ISSUE THREAD

**Issue by arrygoo** [evandhq/react-persian-datepicker#14]
Hey, sweet project. Are there plans in adding a time selector to the project?

**Comment by mohebifar** [comment]
Thanks!
This component was designed for [Evand](https://evand.ir) and it just fulfills its requirements and we have received no PRs yet. It has always been a matter of discussion in Evand whether to put the time picker inside it or not and finally we decided to keep them separated. However, PRs are welcome.

But I'm curious why someone in Ontario may need this? 😂

**Comment by arrygoo** [comment]
Haha, I'm trying to help a friend with a booking system for an [escape game](http://escapeme.eu/persian.html) he's making in Tehran. It's actually a pretty cool puzzle they've made if you want to try.

I was trying to develop the booking system in Meteor for him, and was looking for a date picker. Yours seems to be the most elegantly written one, but I wasn't able to get it to work with Meteor out of the box since obviously it's not designed for that purpose. Maybe once I have more Meteor 1.3 experience I'll try to port it.
