### ISSUE TITLE
Problem with styles when not using CSS Modules

### ISSUE THREAD

**Issue by morajabi** [evandhq/react-persian-datepicker#19]
I believe It's better to use plain css / inline in order to not cause problems with project not offering css modules.

**Comment by thg303** [comment]
Use this css file. I gathered it from the one in the repository. don't forget to fix the extension to ".css"
[evan-calender-style.css.txt](https://github.com/evandhq/react-persian-datepicker/files/785143/evan-calender-style.css.txt)

**Comment by mohebifar** [comment]
If you're not using css-modules, as stated in the [README](https://github.com/evandhq/react-persian-datepicker/blob/190ff9015bd2a619ce3df72d8caccd82cea6da85/README.md#usage) you can pass a css-module-ish object:

```js
const styles = {
    referenceClassName: 'classNameInYourCSS',
    ...
};
```

You can find all the reference CSS classes [here](https://github.com/evandhq/react-persian-datepicker/blob/master/src/styles/basic.css)

**Comment by pouriaMaleki** [comment]
Hey guys, amazing job, thanks.

I think styles object should pass over "calendarStyles" prop not styles according to mentioned code line below.

https://github.com/evandhq/react-persian-datepicker/blob/master/src/components/DatePicker.js#L144
