### ISSUE TITLE
DataPicker

### ISSUE THREAD

**Issue by ssageghi** [evandhq/react-persian-datepicker#20]
Hi
I have a sign-up process that user choose birthday and it's fine
but I want to use DataPicker in edit menu of user that sign-up 
how can I show the previous value of birthday and then change it?
thank for your help

**Comment by thg303** [comment]
same issue here. looks like can't re-assign value from moment object

**Comment by thg303** [comment]
Assign "**defaultValue**" instead of "value". checkout this example:
```
<DatePicker
 onChange={value => {  setValue('birthday', value) }}
 defaultValue={moment()}
/>
```

**Comment by ssageghi** [comment]
thank you
it's working
