### ISSUE TITLE
Controlled input usage

### ISSUE THREAD

**Issue by pouriaMaleki** [evandhq/react-persian-datepicker#24]
The code below will cause state change loop although it's regular in [React](https://facebook.github.io/react/docs/forms.html#controlled-components) community (Ex. material-ui components)

```
onChange(value) {
  this.setState({dateValue: value});
}

render() {
  return <DatePicker value={@state.dateValue} onChange={this.onChange.bind(this)} />
}
```

**Comment by mohebifar** [comment]
Can provide more information on this so I can reproduce the issue? [What you see in the examples](https://github.com/evandhq/react-persian-datepicker/blob/master/examples/src/components/App.js#L56) are the same and they are working fine.

**Comment by pouriaMaleki** [comment]
Sorry it was correct in someway, but the problem shows up when I was doing this:

```
onChange(value) {
  this.setState({dateValue: value.toISOString()});
}

render() {
  return <DatePicker value={new moment(@state.dateValue)} onChange={this.onChange.bind(this)} />
}
```

And I had to do that because I fetch some data from server and show it in my form like this:

```
someButtonAction() {
  getDataFromServer().then(function(data){
     this.setState({ value: data.date });
  });
}
```

And this will cause repetitive setState in onChange and code gonna stuck in loop.

Another problem with this value is I can't clean it up like this:

```
cleanUpForm() {
  this.setState({ value: null });
}
```

**Comment by mohebifar** [comment]
Why not normalizing it (in this case, making the moment object out of
the formatted datetime string) only once when you fetch the initial form values
from the server?

**Comment by pouriaMaleki** [comment]
That will fix first problem, but still weird behavior on initial value, and unable to clean it up. It may happen because of keeping date `value` inside `DatePicker ` component by using `state` and not fully relay on `prop.value` (as it's regular on [controlled components](https://facebook.github.io/react/docs/forms.html#controlled-components)).

This simply shows nothing in first render:
```
render() {
  return <DatePicker value={new moment()} />
}
```

and this (or any other empty value) will not clear input:
```
cleanUpForm() {
  this.setState({ value: null });
}
```

**Comment by mohebifar** [comment]
You are right. Frankly, I do not use this package anymore, specifically the latest version (v3) which I just did for Evand without myself using it in a real project. I'll try to investigate on this. I can't really say when, but probably in this month. Meanwhile, PRs are very welcome :)

**Comment by pouriaMaleki** [comment]
Not very clean solution, but I've made a [PR](https://github.com/evandhq/react-persian-datepicker/pull/25). 

Thanks dude :-)
