### ISSUE TITLE
bug in selected day

### ISSUE THREAD

**Issue by vmtco** [evandhq/react-persian-datepicker#5]
Hi, goto farvardin 1394, see two "1" in this month and selected day not correct

**Comment by mohebifar** [comment]
I'm not sure what you mean. There are two "1"s on the calendar but the second one does not belong to Farvardin. That is for Ordibehesht and once you select it, it goes to the next month because the selected day is on that month.

Thanks for posting an issue.

**Comment by vmtco** [comment]
![bug](https://cloud.githubusercontent.com/assets/2614015/10727310/faabd326-7bed-11e5-881b-5b3a32959037.png)

**Comment by mohebifar** [comment]
Are your running a certain version of the package locally? Can you explain on which cases it happens? I don't see anything similar.

**Comment by vmtco** [comment]
no, just click on demo link and goto Farvardin 1394, i see it.

![faabd326-7bed-11e5-881b-5b3a32959037](https://cloud.githubusercontent.com/assets/2614015/10729455/a5011b82-7bfe-11e5-9ae4-885cb662ddfb.png)
