### ISSUE TITLE
Use in asp.net mvc

### ISSUE THREAD

**Issue by iMashhadi** [evandhq/react-persian-datepicker#7]
hi
This is excellent.
how can use it in asp ?
because input tag not customizable.
actually use tetxtboxfor instead input tag with custom css class.
and why for use "Date Picker Input" we must use <div id="basic-calendar" style="display:none;"></div> on page ? 
thanks

**Comment by mohebifar** [comment]
I regret to tell you that I am not familiar with ASP. However, you can actually customize the input tag by passing a `props` object to the `formatterInput` prop.

You can create your own `DatePicker` component using `Calendar` regarding to ASP's requirements.
