### ISSUE TITLE
Using with Metero.js

### ISSUE THREAD

**Issue by tomvolek** [evandhq/react-persian-datepicker#8]
HI MO  : 
   HI can you port this great datepicker to Metero.js ? :)     Meteor.js can really use this ..

**Comment by mohebifar** [comment]
Not sure if I'm gonna do that. But I'd be happy to see a PR on it.

**Comment by arrygoo** [comment]
+1 for this. 
@tomvolek If you find any guidelines on porting such libraries to Meteor I'd be willing to tackle this.

**Comment by alireza-ahmadi** [comment]
With the introduction of Meteor's **new module system** in version 1.3, we can use this component in the meteor projects in the same way we use it in other projects, just install the `react-persian-datepicker` by running the following command:

``` bash
meteor npm install --save react-persian-datepicker
" or simple by running npm install without meteor prefix
```

And then importing the required parts of the module to your project's `client` files:

``` js
import { Calendar } from 'react-persian-datepicker';
// if you want to use the packages's default CSS
import 'react-persian-datepicker/css/basic.css';
```

It works flawlessly, so I think there is no need for creating a separate Atmosphere package and this issue should get closed.

**Comment by mohebifar** [comment]
Thanks @alireza-ahmadi.
Ping @arrygoo @tomvolek. Let me know if it works for you.

**Comment by arrygoo** [comment]
Thanks @alireza-ahmadi!
I agree, with 1.3 you can just use this out of the box.

**Comment by tomvolek** [comment]
Thanks Alireza. will give it a try .good work  

```
On Wednesday, July 13, 2016 7:28 PM, Alireza Ahmadi <notifications@github.com> wrote:
```

 With the introduction of Meteor's new module system in version 1.3, we can use this component in the meteor projects in the same way we use it in other projects, just install the react-persian-datepicker by running the following command:meteor npm install --save react-persian-datepicker
" or simple by running npm install without meteor prefixAnd then importing the required parts of the module to your project's client files:import { Calendar } from 'react-persian-datepicker';
// if you want to use the packages's default CSS
import 'react-persian-datepicker/css/basic.css';It works flawlessly, so I think there is no need for creating a separate Atmosphere package and this issue should get closed.—
